<a href="https://colab.research.google.com/github/gabiacuna/KL2021/blob/main/1-Python%20y%20Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a Colab, Python y Herramientas de Trabajo


Python es un lenguaje poderoso y fácil de aprender. Posee estructuras de datos de alto nivel y una enfoque simple de orientación a objetos.

Python permite dividir los programas en módulos que pueden ser reutilizados por otros programas. Adicionalmente, viene con una gran colección de módulos propios para realizar tareas de entrada y salida, llamadas al sistema, sockets, interfaces gráficas, etc.

Python es un lenguaje interpretado. Esto quiere decir que para ejecutar un programa en este lenguaje se requiere la instalación de un intérprete. El intérprete puede ser usado interactivamente, lo cual hace fácil experimentar con características del lenguaje.


## Colaboratory (Colab)

Es una herramienta web de Google que permite ejecutar código en python:

- Sin realizar configuración adicional
- Con acceso gratis a GPU
- Es fácil de compartir

Los códigos en colab se conocen como notebooks.


Para cargar este notebook se debe:

1. Ingresar a https://colab.research.google.com/notebooks/intro.ipynb#recent=true

![](https://raw.githubusercontent.com/arleserp/MinTIC2022/master/images/opennotebook.png "Open Notebook")

2. Seleccionar github e ingresar los datos como se muestra a continuación:



![](https://raw.githubusercontent.com/arleserp/CCE2021/main/images/opennotebook.png "Open Notebook")

Y listo!

![](https://raw.githubusercontent.com/arleserp/CCE2021/main/images/opennotebook2.png "Open Notebook2")

En colab existen dos tipos de celda Texto y Código. Esta es una celda de texto.

In [1]:
# esta es una celda de código
x = "amigos"
print("hola " + x)

hola amigos


Para ejecutar una celda se puede presionar el boton de play ó con el teclado escribir:

- ```Command/Ctrl+Enter```: ejecuta y se mantiene en la celda.
- ```shift+Enter```: ejecuta y pasa a la siguiente celda.

En los campos de texto se puede usar algo de html:

<table>
    <tr>
    <td>Nombre Estudiante</td><td>Nota</td>
    </tr>
    <tr>
    <td>Mike Myers</td><td>4.5</td>
    </tr>
    <tr>
    <td>Otm Shank</td><td>2.3</td>
    </tr>
</table>

ó incluso código en Latex:

$\sum_{i=1}^{n}{i^2}$

El valor de una variable definida en una celda de código se puede usar en las celdas siguientes:

In [ ]:
print("Eso es todo " + x)

Eso es todo amigos


## Resumen de algunas cosas útiles de python

### Identificadores y variables en python

Un *identificador* es una secuencia de símbolos que se utilizan como nombres de variables, funciones, clases y otras estructuras de los lenguajes de programación.

Los identificadores se escriben como secuencias de caracteres alfanuméricos del alfabeto inglés. En python se utiliza una notación conocida como snake_case (ó palabras en minúsculas separadas por guiones) para evitar utilizar espacios como por ejemplo: conteo_animales, nombre_usuario, velocidad, etc. Se recomienda utilizar únicamente letras del alfabeto inglés a la hora de usar identificadores.

Son ejemplos de identificadores válidos:

```
i
x
suma
sumando1
sumando2
edad 
pais_de_nacimiento
nombre 
area_circulo

```

## Tipos de datos escalares

Los programas manipularán diferentes tipos de datos. Cada objeto tiene un tipo de datos asociado a el. Se tienen tipos de datos escalares que corresponden a: 

- `int` representa números enteros ejemplo: 5, -5
- `float` representa números reales 3.27
- `bool` representa valores booleanos `True` y `False`
- `Nonetype` es especial y tiene un único valor `None`

es posible usar type() para ver el tipo de dato de un objeto:

In [ ]:
x = 5.6e12
type(x)

float

In [ ]:
type(5) 

int

## Operaciones aritméticas y lógicas

- Suma: +
- Resta: -
- Multiplicación: *
- División entera: //
- División real: /
- Residuo: %
- Potencia: **
- Asignación: =
- Asignación con suma: +=
- Asignación con resta: -=

A continuación se muestran algunos ejemplos de operaciones básicas:

In [ ]:
#división que te va a dar como resultado un número real.
y = 7/3
print(y)


2.3333333333333335


In [ ]:
#División que te va a dar como resultado un número entero
c = 7//3
print(c)

2


In [ ]:
y =  4 * 6
z = 5
y += z
print(y)

29


### Operadores lógicos y de Comparación:

Python posee los siguientes operadores lógicos básicos:

- ```and, or, not``` 

Y los siguientes operadores de comparación:

- ```a == b```: retorna verdadero si los valores de a y b son iguales, falso en otro caso.
- ```a != b ```: retorna verdadero si los valores son diferentes, falso en otro caso.
- ```a >= b```: retorna verdadero si a es mayor o igual a b. 
- ```a > b```: retorna verdadero si a es mayor a b. 
- ```a <= b```: retorna verdadero si a es menor o igual a b.
- ```a < b```: retorna verdadero si a es menor a b.

A continuación algunos ejemplos:

In [ ]:
a = 3
b = 4

print(a == b)

False


In [ ]:
x = 3
y = 5
print(x > y)

False


### Funciones y estructuras de control en python

La definición del método que calcula el área de un rectángulo constituye un bloque de código (en python se llama suite) que inicia con la palabra def y termina en la línea 2 con la instrucción ```return l*a```. Python utiliza la indentación para definir suites. Una forma rápida de identificar una suite en python es porque inicia con ```:```. 



In [ ]:
def area_rectangulo(l, a):
  return l*a #vemos que esto está definido dentro del método

area_rectangulo(3,5)

15

A parte de definir métodos, se utilizan los dos puntos ```:``` para definir las estructuras de control condicional ```if else elif``` y las estructuras de control cíclico ```for while```.


### Estructuras de control condicional

Es posible determinar que suite de código ejecutar especificando estructuras de control condicional. Por ejemplo para determinar si un número es par podríamos decir que un número par es aquel cuyo residuo entre 2 es igual a cero, de otro modo es impar.


In [ ]:
def es_par(num):
  if num % 2 == 0:
    print(num, 'es par')
  else:
    print(num, 'es impar')

num = int(input('digite un número: '))
es_par(num)

digite un número:  4


4 es par


Es posible tener más de dos casos en una estructura de control condicional, como veremos en el siguiente ejemplo: La empresa Tqm ofrece la siguiente promocion: por compras mayores a 10000 lleva un 10% de descuento. Por compras mayores a 20000 lleva un 20% de descuento. Dado el valor de la compra halle el valor a pagar y diga de cuanto fue el descuento.

In [ ]:
def descuento(vc):
  if vc > 10000 and vc <= 20000:
    print("valor a pagar", vc-vc*0.1, "y ahorró:" , vc*0.1)
  elif vc > 20000:
    print("valor a pagar", vc-vc*0.2, "y ahorró:" , vc*0.2)
  else:
    print("usted compró muy poco y no tiene descuentos.")
  
vc = int(input('digite el valor total de su compra:'))
descuento(vc)

digite el valor total de su compra: 45555


valor a pagar 36444.0 y ahorró: 9111.0


### Estructuras de control cíclico y algunas estructuras de datos

### El ciclo while 

El ciclo ```while``` permite ejecutar un bloque de instrucciones mientras que una expresión booleana dada se cumpla, es decir, mientras su evaluación dé como resultado verdadero. La expresión booleana se denomina condición de parada y siempre se evalúa antes de ejecutar el bloque de instrucciones. Si la condición no se cumple, el bloque no se ejecuta. Si la condición se cumple, el bloque se ejecuta, después de lo cual la instrucción vuelve a empezar, es decir, la condición se vuelve a evaluar.

En el caso en que la condición se evalúe la primera vez como falsa, el bloque de instrucciones no será ejecutado, lo cual quiere decir que el número de repeticiones o iteraciones de este bloque será cero. Si la condición siempre evalúa a verdadero, la instrucción se ejecutará indefinidamente, es decir, un número infinito de veces.

La estructura de un ciclo ```while``` se da en el siguiente fragmento de código:

```
<suite_prev>
<inicia>
while(<cond>):
  <suite_while>
  <actualiza>
<suite_siguiente>

```

Donde: 

- El fragmento suite_prev es la suite instrucciones previas que han sido ejecutadas antes del ciclo.

- El fragmento inicia es la suite de instrucciones donde se inicializan las variables que intervienen en la condición de parada.

- El fragmento cond es la condición de parada que se evalúa cada vez que se inicia o se reinicia el ciclo.

- El fragmento suite_while es el bloque de instrucciones principal del ciclo que se ejecuta mientras la condición se  cumpla.

- El fragmento actualiza es el bloque que se utiliza para actualizar las variables que son utilizadas para evaluar la condición de parada cuando se intenta reiniciar el ciclo.

- El fragmento suite_siguiente es el bloque de instrucciones que se  ejecutan después de terminar de ejecutar el ciclo.

A continuación se muestra un ejemplo de funcionamiento del ciclo while. Se utilizarán métodos para introducir al lector en la programación modular.


In [ ]:
%%time 
#mide el tiempo de ejecución de una celda

import time #es para usar sleep

def ejemplo_while():
  #sirve para determinar el tiempo de ejecución de un programa 
  i = 2 #inicializa a i en 2
  j = 25 # inicializa a j en 25

  while i < j: #mientras i sea menor a j
      print(i, ",", j) #va a imprimir los valores de i , j
      #time.sleep(0.004) #función que interrumpe 
      i*=2 # i = i*2 como a i lo va multiplicando por 2 en cada paso se espera que supere a j en un punto
      j+=10 # j = j + 10 se incrementa de 10 en 10
  
  print("the end.") #esta es una instrucción que se ejecuta al terminar el ciclo while
  print(i, ",", j) #imprime los valores finales de i y de j
  print("esto es parte de la función")


ejemplo_while() #aquí se llama el método


2 , 25
4 , 35
8 , 45
16 , 55
32 , 65
64 , 75
the end.
128 , 85
esto es parte de la función
Wall time: 1.98 ms


### Tuplas

Una tupla es una secuencia de elementos que puede almacenar datos heterogeneos tales como: float, strings, listas y diccionarios. Como los strings, las tuplas son inmutables.


In [ ]:
tup = (1, 2, 3, 4.6, 'hola', 'a')
print(tup)

(1, 2, 3, 4.6, 'hola', 'a')


Se pueden recorrer los elementos de una tupla con for:

In [ ]:
for dato in tup:
    print(dato, end=" ")

1 2 3 4.6 hola a 

Para acceder a un valor particular de una tupla se especifica su posición con corchetes ```[]```:

In [ ]:
avengers = ("Ironman", "Spiderman", "Ant-man", "Hulk", "Thor", "The Wasp")

In [ ]:
avengers[0]

'Ironman'

In [ ]:
avengers[-1]

'The Wasp'

In [ ]:
avengers[1:3]

('Spiderman', 'Ant-man')

In [ ]:
avengers[::-1]

('The Wasp', 'Thor', 'Hulk', 'Ant-man', 'Spiderman', 'Ironman')

### Funciones de Tuplas 

Longitud de la tupla: 

In [ ]:
tup = (1,2,3,4)
len(tup)

4

Máximo elemento de una tupla:

In [ ]:
t = (4,5,-1,6,7) 
max(t)

7

Mínimo elemento de una tupla:

In [ ]:
min(t)

-1

### Listas 

Una lista es muy similar a la noción de un arreglo. En este sentido puede entenderse como una colección indexada de objetos. A cada elemento le corresponde una posición. Una lista puede almacenar objetos de diferente tipo en la misma estructura. Es posible también añadir, remover, o cambiar objetos. Esto quiere decir que las listas son mutables.

In [ ]:
dias = ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado']
print(dias)

temps = [ 32.0, 212.0, 0.0, 81.6, 100.0]
print(temps)

['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado']
[32.0, 212.0, 0.0, 81.6, 100.0]


Para saber si un elemento está en una lista se puede usar el operador in:

In [ ]:
dias = ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado']
if('lunes' in dias):
    print('Si')

Si


Una lista puede almacenar distintos tipos de dato:

In [ ]:
car_details = ['Toyota', 'RAV4', 2.2, 60807]

for detail in car_details:
    print("dato " + str(detail) + " tipo: " + str(type(detail)))

dato Toyota tipo: <class 'str'>
dato RAV4 tipo: <class 'str'>
dato 2.2 tipo: <class 'float'>
dato 60807 tipo: <class 'int'>


Si se desea tener la posición de un elemento y el elemento se puede usar enumerate:


In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(f"{idx + 1}: {animal}")
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

1: cat
2: dog
3: monkey


Es posible tener una lista de listas:

In [ ]:
mi_lista = [[1,2,3], ['a', 'b', 'c']]

print(mi_lista)

print(mi_lista[0])
print(mi_lista[1])
print(mi_lista[1][1])

[[1, 2, 3], ['a', 'b', 'c']]
[1, 2, 3]
['a', 'b', 'c']
b


Para crear la lista y añadir elementos de forma dinámica se puede hacer lo siguiente:

In [ ]:
found=[] #se crea la lista vacía
len(found) #este método calcula la longitud de la lista


0

In [ ]:
found.append('a')
found.append('e')
found.append('i')
found.append('o')
found.append('u')
print(found, len(found))

['a', 'e', 'i', 'o', 'u'] 5


Es posible crear una lista a partir de otra. Esto se conoce como listas por comprensión. El siguiente código:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


Es equivalente a:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


Tambien es posible remover la ocurrencia de un valor específico en la lista. Remove toma como argumento el objeto que se va a eliminar, remueve el elemento de la lista y reduce en uno su tamaño. Si el elemento no se encuentra en la lista se lanza un error.

In [ ]:
found.remove('i')
print(found)
print(len(found))

['a', 'e', 'o', 'u']
4


En el caso en el que se requiera eliminar un elemento de una posición específica de la lista. El método pop recibe como parámetro la posición del elemento a remover. Las posiciones en las listas empiezan en cero. Si no se especifican parámetros, se remueve el último elemento de la lista.

In [ ]:
nombres = ['Jaime', 'Johan', 'Monica', 'María', 'Mabel']
print(nombres)
nombres.pop(1) #remueve a Johan
print(nombres)
nombre_borrado = nombres.pop() # remueve a Mabel
print(nombre_borrado + " ha sido eliminada de la lista.")
print(nombres)

['Jaime', 'Johan', 'Monica', 'María', 'Mabel']
['Jaime', 'Monica', 'María', 'Mabel']
Mabel ha sido eliminada de la lista.
['Jaime', 'Monica', 'María']


Es posible agregar una lista al final de otra lista. Para esto se puede utilizar el método extend.

In [ ]:
nombres = ['Jaime', 'Johan', 'Monica', 'María', 'Mabel']
otros_nombres = ['Barry', 'John', 'Guttag']

nombres.extend(otros_nombres)
print(nombres)

['Jaime', 'Johan', 'Monica', 'María', 'Mabel', 'Barry', 'John', 'Guttag']


Para agregar elementos en una posición específica de una lista se puede utilizar el método insert:

In [ ]:
nombres = ['Jaime', 'Johan', 'Monica', 'María', 'Mabel']
nombres.insert(0, 'Guttag') #posición valor
nombres.insert(2, 'Peter') #list_name.insert(posición,valor)
nombres.insert(len(nombres)//2, 7891247812)
print(nombres)

['Guttag', 'Jaime', 'Peter', 7891247812, 'Johan', 'Monica', 'María', 'Mabel']


Como pedir ayuda sobre un método específico:

In [ ]:
help(list.append)

Help on method_descriptor:

append(self, object, /)
    Append object to the end of the list.



In [ ]:
??list

Init signature: list(iterable=(), /)
Docstring:     
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
Type:           type
Subclasses:     _HashedSeq, StackSummary, SList, _ImmutableLineList, FormattedText, NodeList, _ExplodedList, Stack, _Accumulator, _ymd, ...


### Manejando Conjuntos en Python

Los conjuntos en python pueden ser muy útiles para eliminar datos duplicados. Si se tiene una lista de nombres que puede estar duplicada, basta con convertirla en conjunto para eliminar los datos duplicados. Esta estructura también está optimizada para buscar datos pues las listas realizan una búsqueda secuencial. Los datos no se almacenan necesariamente en orden.

In [ ]:
vocales = {'a', 'e', 'i', 'o', 'u', 'a', 'a', 'o', 'e'}
print(vocales)

{'o', 'e', 'a', 'i', 'u'}


Es posible ordenar un conjunto así:

In [ ]:
['a', 'e', 'i', 'o', 'u']

['a', 'e', 'i', 'o', 'u']

Se pueden crear conjuntos a partir de listas o tuplas:

In [ ]:
l_vocals = ['a', 'e', 'i', 'o', 'u', 'i']
vocalsl = set(l_vocals)
print(vocalsl)

{'o', 'e', 'a', 'i', 'u'}


Es posible unir dos conjuntos:

In [ ]:
seta = set('murcielago')
setb = set('externocleidomastoideo')
setc = seta.union(setb)
print(setc)

{'o', 'a', 'i', 'l', 't', 'r', 'g', 's', 'u', 'd', 'n', 'x', 'c', 'm', 'e'}


Se puede calcular la diferencia entre dos conjuntos. Permite examinar los datos que están en un conjunto de palabras que no están en otro:

In [ ]:
stop_wordsA = {'el', 'un', 'la', 'los'}
stop_wordsB = {'un', 'una', 'unos', 'el'}

Para determinar los elementos que están en stop_wordsA que no están en stop_wordsB basta con:

In [ ]:
stop_wordsA - stop_wordsB

{'la', 'los'}

Para determinar los elementos que tienen en común los conjuntos de stop_words (intersección):

In [ ]:
stop_wordsB & stop_wordsA

{'el', 'un'}

La diferencia simétrica consiste en encontrar elementos que están en la unión de dos conjuntos pero no en la intersección

In [ ]:
stop_wordsB ^ stop_wordsA

{'la', 'los', 'una', 'unos'}

### Diccionarios 

Así como en una lista los valores están indexados por su posición, en un diccionario los valores van a estar indexados por sus llaves. La sintaxis de un diccionario es:

```nombre_dict = { key1: value1, key2: value2}

In [ ]:
port = { 22: 'SSH', 23: 'Telnet', 80: 'HTTP', 3306: 'MySQL'}

Cada pareja llave valor es considerada un ítem. La llave y el valor están separados por ```:```, cada ítem está separado por comas ```,``` y los items están rodeados por llaves ```{``` ```}```. Un diccionario vacío puede crearse así: ```{}```. Las características clave de un diccionario son:

- La llave de un ítem no puede ser cambiada
- Un string, int, o float puede ser usado como llave.
- Una tupla que no contenga listas puede ser usada como llave.
- Las llaves son únicas.
- Los valores pueden ser cualquier tipo de dato.
- Los valores pueden estar repetidos.
- Los valores pueden ser cambiados.
- Un diccionario es una colección desordenada (el orden en el que se ingresen los datos es independiente de la forma en la que se almacenan en la estructura de datos).

Para acceder a un valor en un diccionario es necesario tener la llave.

In [ ]:
port = { 22: 'SSH', 23: 'Telnet', 80: 'HTTP', 3306: 'MySQL'}

In [ ]:
protocol = port[22]
print(protocol)

SSH


Si la llave no está se produce un KeyError:

In [ ]:
port[443]

KeyError: 443

Con del es posible eliminar el diccionario entero o los ítems de un diccionario. Si se desea eliminar un ítem se puede utilizar la siguiente sintaxis:

In [ ]:
port = { 22: 'SSH', 23: 'Telnet', 80: 'HTTP', 3306: 'MySQL'}
print(port)
del port[23]
print(port)

{22: 'SSH', 23: 'Telnet', 80: 'HTTP', 3306: 'MySQL'}
{22: 'SSH', 80: 'HTTP', 3306: 'MySQL'}


Para añadir un valor se realiza la asignación:

```dict[new_key] = new_val```

In [ ]:
port = {80: "HTTP", 23 : "SMTP", 443 : "HTTPS"}
print(port)
port[110] = 'POP'
print(port)

{80: 'HTTP', 23: 'SMTP', 443: 'HTTPS'}
{80: 'HTTP', 23: 'SMTP', 443: 'HTTPS', 110: 'POP'}


Es posible convertir una lista de listas o una lista de tuplas en un diccionario usando dict.

In [ ]:
port = [[80,"http"],[20,"ftp"],[23,"telnet"],[443,"https"],[53,"DNS"]]
d_port = dict(port)
print(d_port)

{80: 'http', 20: 'ftp', 23: 'telnet', 443: 'https', 53: 'DNS'}


Para validar la existencia de la llave en un diccionario se puede utilizar el operador in:

In [ ]:
print(80 in d_port)
print(222 in d_port)

True
False


Para obtener una lista de las llaves se puede hacer lo siguiente:

In [ ]:
dict1 = {'a':1, 'b':2, 'c':3}
print(list(dict1.keys()))

['a', 'b', 'c']


## Una librería muy útil: numpy

Es una de las librerías más conocidas para realizar computación científica en python. Provee una libería de alto rendimiento para la manipulación de arreglos en varias dimensiones. Y ofrece herramientas para trabajar en arreglos.

### Arrays en numpy

Un arreglo en numpy es una retícula de valores del mismo tipo indexadas por enteros no negativos. El número de dimensiones ```rank``` y la forma ```shape``` del arreglo es una tupla de enteros que da el tamaño del arreglo para cada dimensión.

Se pueden crear arreglos de numpy desde listas de python y acceder a los elementos con el operador subscript ```[]```

In [ ]:
import numpy as np

a = np.array(list(range(1,5)))   # Crea una lista que contiene 1 2 3 4

print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a)
print(a.shape)            # Prints "(4,)" porque es una dimensión de tamaño 4
print(a[0], a[1], a[2])   
a[0] = -4                  
print(a)                  

b = np.array([[1,2,3,5,6],[4,5,6,7,8]])    # Create a rank 2 array
print(b.shape)  
print(b)
b[0,0] = 1590
print(b)
print(b[0, 0], b[0, 1], b[1, 0])  

<class 'numpy.ndarray'>
[1 2 3 4]
(4,)
1 2 3
[-4  2  3  4]
(2, 5)
[[1 2 3 5 6]
 [4 5 6 7 8]]
[[1590    2    3    5    6]
 [   4    5    6    7    8]]
1590 2 4


Es posible crear arreglos de diferente tipo de forma muy rápida:

In [ ]:
import numpy as np

a = np.zeros((2,3,4))   # Crea un arreglo de ceros de 3 dimensiones 
print(a.shape)        
print(a)  
print('---------')

b = np.ones((2,3))    # Crea un arreglo de 1
print(b.shape)
print(b)
print('---------')

c = np.full((3), 7)  # Crea un arreglo de rango 1 con contenido 7
print(c.shape)
print(c)
print('---------')
        
d = np.eye(3)         # Crea un arreglo identidad de 3 x 3
print(d.shape)
print(d)              
print('---------')

e = np.random.random((2,3))  # Crea un arreglo de rango 3 con valores al azar
print(e.shape)
print(e)  

(2, 3, 4)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
---------
(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]
---------
(3,)
[7 7 7]
---------
(3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------
(2, 3)
[[0.02028961 0.9508226  0.62258264]
 [0.9607978  0.34749103 0.29140549]]


El operador subscript funciona en numpy

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a.shape)
print(a)
print(a[:2])

b = a[:2, 1:3]
print("b", b)

print('------------------------')


# modificar una porción del array b cambia el contenido de a
b[0, 0] = -11     # b[0, 0] is the same piece of data as a[0, 1]
print(b)
print(a)
print(a[0, 1])   # Prints "-11"

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
b [[2 3]
 [6 7]]
------------------------
[[-11   3]
 [  6   7]]
[[  1 -11   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
-11


Se puede mezclar indexado entero con indexado por partes. Esto retornará un arreglo de menor dimensionalidad que el arreglo original.

In [ ]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)
print(a.shape)
print('-----------------')
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
-----------------
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Indexamiento booleano: Permite selecionar elementos que cumplan con una cierta condición.

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   
print(bool_idx)      

print(a[bool_idx])  #array de elementos mayores a 2

#una expresión equivalente
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


Numpy como python determina el tipo de dato basado en el valor. Sin embargo dicho tipo también puede especificarse:

In [ ]:
import numpy as np

x = np.array([5, -4])   
print(x.dtype)         

x = np.array([1.0, 2.0])   
print(x.dtype)          

x = np.array([5, -4], dtype=np.int64)   
print(x.dtype) 

int32
float64
int64


### Operaciones elementwise

Son operaciones elemento a elemento:

In [ ]:
import numpy as np

x = np.array([[1,2,5],[3,4,6]], dtype=np.float64)
y = np.array([[5,6,-1],[7,8,-6]], dtype=np.float64)

print('Suma:')
print(x + y)
print('-----')
print(np.add(x, y))

print('Resta:')
print(x - y)
print('-----')
print(np.subtract(x, y))

print('Multiplicación:')
print(x * y)
print('-----')
print(np.multiply(x, y))

print("División:")
print(x / y)
print('-----')
print(np.divide(x, y))

print("raiz cuadrada:")
print(np.sqrt(x))

Suma:
[[ 6.  8.  4.]
 [10. 12.  0.]]
-----
[[ 6.  8.  4.]
 [10. 12.  0.]]
Resta:
[[-4. -4.  6.]
 [-4. -4. 12.]]
-----
[[-4. -4.  6.]
 [-4. -4. 12.]]
Multiplicación:
[[  5.  12.  -5.]
 [ 21.  32. -36.]]
-----
[[  5.  12.  -5.]
 [ 21.  32. -36.]]
División:
[[ 0.2         0.33333333 -5.        ]
 [ 0.42857143  0.5        -1.        ]]
-----
[[ 0.2         0.33333333 -5.        ]
 [ 0.42857143  0.5        -1.        ]]
raiz cuadrada:
[[1.         1.41421356 2.23606798]
 [1.73205081 2.         2.44948974]]


### Producto de matrices y Producto Punto

Otra operaciones de interés pueden ser producto de matrices y producto punto

*Producto de matrices*

$$\begin{bmatrix}
1 & 2 & 5\\
3 & 4 & 6
\end{bmatrix}\begin{bmatrix}
8\\
6\\
4
\end{bmatrix} = \begin{bmatrix}
8 + 12 + 20\\
24 + 24 + 24
\end{bmatrix} = \begin{bmatrix}
40\\
72
\end{bmatrix}$$

![](https://raw.githubusercontent.com/arleserp/CCE2021/main/images/multimat.png "Open Notebook")

In [ ]:
x = np.array([[1,2,5],[3,4,6]])
y = np.array([8,6,4])

print(x.shape)
print(y.shape)

print('x:\n', x)
print('Transpose:\n', y.T) #transpuesta de y

p = x @ y.T #producto de matrices
print('Product', p)

(2, 3)
(3,)
x:
 [[1 2 5]
 [3 4 6]]
Transpose:
 [8 6 4]
Product [40 72]


*Producto punto*

- Si a y b son arreglos unidimensionales es el producto punto (inner product) de vectores. 
- Si a y b son arreglos bidimensionales, es una multiplicación de matrices pero usar matmul o a @ b se prefiere.
- Si a o b son escalares el resultado es equivalente a una multiplicación a*b. 

![](https://raw.githubusercontent.com/arleserp/CCE2021/main/images/dotvector.png "Open Notebook")



In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print('Producto punto')
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print('producto matriz / vector')
print(x @ v)
print(x.dot(v))
print(np.dot(x, v))

print('producto matriz / matriz')
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x @ y)
print(x.dot(y))
print(np.dot(x, y))


Producto punto
219
219
producto matriz / vector
[29 67]
[29 67]
[29 67]
producto matriz / matriz
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


#### np.linspace

Retorna desde el número start hasta el número stop num datos:

In [ ]:
import numpy as np

np.linspace(2, 3, num = 15, endpoint = True, retstep = False, dtype = None)

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ])

[video de cosas interesantes con numpy](https://www.youtube.com/watch?v=xECXZ3tyONo&t=398s)

## Referencias


Armendáriz, D (2019). Introducción a Jupyter Notebook. Visitado el 2 de Junio de 2020. https://www.youtube.com/watch?v=orr063XGPPE

Barry, P. (2016). Head First Python: A Brain-Friendly Guide. " O'Reilly Media, Inc.".

Guttag, John. Introduction to Computation and Programming Using Python: With Application to Understanding Data Second Edition. MIT Press, 2016. ISBN: 9780262529624.

Tutorial oficial de python 3, disponible en: https://docs.python.org/3/tutorial/interpreter.html

Rodríguez, A (2020). Curso de Programación en Python. https://github.com/arleserp/cursopython

Johnson, J. Python Numpy Tutorial (with Jupyter and Colab) https://cs231n.github.io/python-numpy-tutorial/
