<a href="https://colab.research.google.com/github/gabiacuna/KL2021/blob/main/Analisis%20de%20Imagenes%20con%20DL/000-Introduction-to-Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a Pytorch

**Fecha** : 2021-06-28

## Outline

- ¿Qué es Pytorch?
    - Tensores (vectores, matrices, etc.)
        - Son como las listas de numpy, y se utilizan para las entradas y salidas de los modelos.
        - Los modelos tienen muchas capas, se aplica softmax, que es la prob de que una figura sea un garo o un pajaro, etc.
    - Tipos de elements

Lo desarrollo fb y ayuda a hacer todo lo que es el modelaje de forma mas simple

Es mas utilizado en industria. Para academia se utiliza mas tensorflow.

### 1 - Tensores

Los tensores son los elementos que se usan como entradas y salidas de un modelo, al igual que que se
pueden usar como los parámetros del modelo.

Los tensores se parecen mucho a los `numpy arrays`. Una de las diferencias es que los tensores
se pueden usar en hardware como un GPU para acelerar el procesamiento de modelos de Deep Learning.
Los tensores también son objectos que se pueden optimizar, lo cual ayudará mucho para cuando se 
esté entrenando un modelo.

#### 1.1 Iniciando un tensor

Para empezar a utilizar los tensores de Pytorch, uno tiene primero que importar el módulo a la
sesión actual:

In [2]:
#%load_ext lab_black

# Importando módulos
import torch
import numpy as np

Uno puede definir un tensor simplemente con: 

In [16]:
x = torch.empty(1)
print(x)

tensor([-4.5821e-38])


In [17]:
type(x)

torch.Tensor

Este tensor en un valor escalar, y por lo tanto se puede extraer su valor con:
\* Extraemos su valor escalar

In [18]:
x.item()

-4.582071096293804e-38

In [19]:
loss_val = x.item()
loss_val

-4.582071096293804e-38

Similarmente, uno puede definir un tensor de varios elementos:

In [22]:
# Vector de 3 elements y 1 eje
x = torch.empty(3)
print(x)

tensor([-4.5821e-38,  3.0620e-41,  1.6115e-43])


Ya cuando los modelos son más complejos y requieren de más dimensiones, Pytorch lo deja a uno
definir tensores de varias dimensiones. Esto es conveniente cuando se tienen modelos con varias
capas ocultas de varias dimensiones:

In [23]:
x = torch.empty(2, 3)
print(x)

tensor([[-4.5821e-38,  3.0620e-41,  1.6115e-43],
        [ 0.0000e+00,         nan,  0.0000e+00]])


In [24]:
x = torch.empty(2, 2, 2, 3)
print(x)

tensor([[[[0.0000e+00, 0.0000e+00, 7.0065e-44],
          [6.8664e-44, 6.3058e-44, 6.7262e-44]],

         [[7.5670e-44, 6.3058e-44, 7.0065e-44],
          [7.9874e-44, 1.1771e-43, 6.7262e-44]]],


        [[[6.7262e-44, 8.1275e-44, 6.7262e-44],
          [7.7071e-44, 8.1275e-44, 6.8664e-44]],

         [[7.2868e-44, 6.4460e-44, 7.2868e-44],
          [7.5670e-44, 7.1466e-44, 7.1466e-44]]]])


In [28]:
# Ver el tamaño del tensor
print(x.size())

torch.Size([2, 2, 2, 3])


O también se puede ver el número total de elementos en el tensor:

In [29]:
print(x.numel())

24


#### 1.2 - Trabajando con Numpy y Tensores

Cuando uno está trabajando con `Numpy` y `Pytorch`, es conveniente convertir elementos
entre Numpy a Pytorch, y vice versa.

Por ejemplo, si definimos un *array* en Numpy, i.e.: `data`

In [30]:
data = np.arange(10)
print(data)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
type(data)

numpy.ndarray

Fácilmente lo podemos convertir a un tensor con la función `torch.from_numpy`:

In [32]:
data_tensor = torch.from_numpy(data)
print(data_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Y el tipo de `data_tensor` es:

In [33]:
type(data_tensor)

torch.Tensor

Similarmente, se puede hacer lo inveso y convertir un tensor a un *array* en Numpy:

In [34]:
data_to_numpy = data_tensor.numpy()
print(data_to_numpy)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
type(data_to_numpy)

numpy.ndarray

Una de las tares que uno realiza mayormente cuando trabaja con Pytorch es cambiando
las dimensiones de los tensores. Similarlmente a `Numpy`, Pytorch te deja modificar las
dimensiones de un tensor. Esto resulta muy conveniente cuando las parámetros de entrada
y salida de un modelo tienen diferentes dimensiones:

In [36]:
t = torch.ones(1, 24)
print(t)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1.]])


Ahora podemos modificar las dimensiones del tensor:

In [37]:
t_modificado = t.reshape((3, 8))
print(t_modificado)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [39]:
print(
    "Ahora las dimensiones del tensor son: `{}` filas y `{}` columnas ...".format(
        *t_modificado.shape
    )
)

Ahora las dimensiones del tensor son: `3` filas y `8` columnas ...


Similarmente, uno puede cambiar las dimensiones del tensor sin tener que declarar una nueva
variable.

**Nota** : Cuando se utiliza funciones que terminan con `_` (e.g. `<tensor>.random_(10)`), el objeto
en sí se modifica en **su lugar**.

In [40]:
t_modificado.resize(4, 6)

/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:490: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

Existe una función muy útil, la cuál transforma el tensor sin tener que saber bien las dimensiones del
nuevo tensor, i.e. `<tensor>.view(filas, columnas)`.

In [41]:
t_modificado.view(-1, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
t_modificado.view(-1, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

Al poner un `-1` como argumento de `.view`, Pytorch calcula automaticamente cuáles serían las dimensiones necesarias
para el nuevo tensor.

#### Funciones a tensores

Similar a `Numpy` arrays, los tensores de Pytorch se pueden utilizar como arrays, y también aplicarles funciones para
modificarlos y demás.

In [44]:
# Creamos un tensor de números del 1 al 4
v = torch.Tensor([1, 2, 3, 4])

# Creamos otro tensor de números del 10 al 20
w = torch.Tensor([10, 11, 15, 14])

In [45]:
v

tensor([1., 2., 3., 4.])

In [46]:
w

tensor([10., 11., 15., 14.])

Ahora podemos utilizar funciones como multiplicación, adición, etc.

In [47]:
# La suma de los dos tensores
v + w

tensor([11., 13., 18., 18.])

In [48]:
v * w

tensor([10., 22., 45., 56.])

In [49]:
v / w

tensor([0.1000, 0.1818, 0.2000, 0.2857])

Similarmente, Pytorch tiene estas funciones dentro de su módulo:

In [50]:
torch.mul(v, w)

tensor([10., 22., 45., 56.])

In [51]:
torch.add(w, v)

tensor([11., 13., 18., 18.])

Inclusive podemos utilizar los tensores junto con exponentes, similar a

$$\frac{v^2 + w^3}{v + w}$$

In [53]:
z = (v ** 2 + w ** 3) / (v + w)
z, v, w

(tensor([ 91.0000, 102.6923, 188.0000, 153.3333]),
 tensor([1., 2., 3., 4.]),
 tensor([10., 11., 15., 14.]))

#### 1.3 - Funciones que se puede usar en Pytorch

Pytorch comparte mucho de su API con Numpy. Es por esto que muchas funciones de uso cotidiano en Numpy
son fáciles de adaptar en Pytorch.

Por ejemplo:

In [55]:
# En numpy
np.arange(4, 15)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
# En Pytorch
torch.arange(4, 15)

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Creando lista de ceros**:

In [57]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Números aleatorios**

In [59]:
np.random.rand(20)

array([0.45289721, 0.3052939 , 0.4859247 , 0.28380815, 0.10542501,
       0.83150467, 0.42727383, 0.08524185, 0.39468729, 0.38847723,
       0.35884477, 0.42597008, 0.93509575, 0.93651242, 0.53432998,
       0.98415099, 0.5150331 , 0.52674559, 0.06428069, 0.64549898])

In [60]:
torch.rand(20)

tensor([0.0809, 0.9463, 0.1383, 0.6270, 0.3635, 0.2966, 0.4187, 0.6531, 0.6791,
        0.6170, 0.8118, 0.3494, 0.1311, 0.8287, 0.9114, 0.7995, 0.1527, 0.4161,
        0.0120, 0.9188])

**Matriz de identidad**

Pytorch inclusive include la famosa función: `eye`, la cual crea una matriz
con ceros en toda la matriz excepto a lo largo de la diagonal:

In [61]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [62]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**Concatenar varios tensores**

Pytorch inclusive incluye una función para concatenar 2 tensores:

In [65]:
# En numpy
a = np.arange(10)
b = np.ones(5)

np.concatenate((a, b))

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 1., 1., 1., 1.])

In [68]:
# En Pytorch
a_tensor = torch.arange(10)
b_tensor = torch.ones(10)

c = torch.cat(
    (a_tensor, b_tensor),
)

c, c.numel(), c.size()

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]), 20, torch.Size([20]))

#### 1.4 - Utilizando `requires_grad`

Una de las grandes diferencias entre `Numpy` y `Pytorch` es que Pytorch incluye varias herramientas que hacen la interacción con modelos muy fácil.

pytorch realiza varios calculos automaticamente :3

Por ejemplo, los tensores de Pytorch incluyen métodos / atributos para calcular el "gradient" de una variable reference a o otra variable:

In [75]:
x_sin_grad = torch.tensor([5.5,3])
x_sin_grad

tensor([5.5000, 3.0000])

In [69]:
x = torch.tensor([5.5, 3], requires_grad=True)
x

tensor([5.5000, 3.0000], requires_grad=True)

Al haber agregado el argumento `requires_grad = True`, Pytorch lo reconoce y empezará a calcular los cambios
de esta variable a lo largo del código.

Por ejemplo, si tenemos 2 tensores y ejecutamos ciertas funciones sobre ellas, miraremos lo siguiente:

In [78]:
v = torch.tensor([1, 2], requires_grad=False)

# Multiplicamos `x * v`
z = x * v
z

tensor([5.5000, 6.0000], grad_fn=<MulBackward0>)

Este nuevo tensor `z` ahora tiene un atributo `grad_fn` reference a la multiplicación de `x * v`.

In [79]:
z.grad_fn

In [81]:
a = torch.tensor([30,40])

In [82]:
z/a

tensor([0.1833, 0.1500], grad_fn=<DivBackward0>)